CSMITH_TESTS= \
	CSmith/000.T CSmith/001.T CSmith/002.T CSmith/003.T CSmith/004.T CSmith/005.T CSmith/006.T CSmith/007.T \
	CSmith/008.T CSmith/009.T CSmith/010.T CSmith/011.T CSmith/012.T CSmith/013.T CSmith/014.T CSmith/015.T \
	CSmith/016.T CSmith/017.T CSmith/018.T CSmith/019.T CSmith/020.T CSmith/021.T CSmith/022.T CSmith/023.T \
	CSmith/024.T CSmith/025.T CSmith/026.T CSmith/027.T CSmith/028.T CSmith/029.T CSmith/030.T CSmith/031.T \
	CSmith/032.T CSmith/033.T CSmith/034.T CSmith/035.T CSmith/036.T CSmith/037.T CSmith/038.T CSmith/039.T \
	CSmith/040.T CSmith/041.T CSmith/042.T CSmith/043.T CSmith/044.T CSmith/045.T CSmith/046.T CSmith/047.T \
	CSmith/048.T CSmith/049.T CSmith/050.T CSmith/051.T CSmith/052.T CSmith/053.T CSmith/054.T CSmith/055.T \
	CSmith/056.T CSmith/057.T CSmith/058.T CSmith/059.T CSmith/060.T CSmith/061.T CSmith/062.T CSmith/063.T \
	CSmith/064.T CSmith/065.T CSmith/066.T CSmith/067.T CSmith/068.T CSmith/069.T CSmith/070.T CSmith/071.T \
	CSmith/072.T CSmith/073.T CSmith/074.T CSmith/075.T CSmith/076.T CSmith/077.T CSmith/078.T CSmith/079.T \
	CSmith/080.T CSmith/081.T CSmith/082.T CSmith/083.T CSmith/084.T CSmith/085.T CSmith/086.T CSmith/087.T \
	CSmith/088.T CSmith/089.T CSmith/090.T CSmith/091.T CSmith/092.T CSmith/093.T CSmith/094.T CSmith/095.T \
	CSmith/096.T CSmith/097.T CSmith/098.T CSmith/099.T CSmith/100.T CSmith/101.T CSmith/102.T CSmith/103.T \
	CSmith/104.T CSmith/105.T CSmith/106.T CSmith/107.T CSmith/108.T CSmith/109.T CSmith/110.T \
